online_store:
  outputs:
    dev:
      #account: xxxx
      #database: airbyte_database
      #password: password
      #role: AIRBYTE_ROLE
      #schema: AIRBYTE_SCHEMA
      #threads: 200
      #type: snowflake
      #user: AIRBYTE_USER
      #warehouse: AIRBYTE_WAREHOUSE
      dataset: dwh_online_store
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/abay/conf/ff-ngulik-de-08293b29731a.json
      location: US
      method: service-account
      priority: interactive
      project: ff-ngulik-de
      threads: 1
      type: bigquery
  target: dev